#!/bin/sh

# java behaves badly in non-reparenting window managers (e.g. xmonad)
export _JAVA_AWT_WM_NONREPARENTING=1

# Remap caps lock to escape
setxkbmap -option caps:escape

# Remap right alt to compose key
setxkbmap -option compose:ralt

eval $(gnome-keyring-daemon --start --components=secrets)
export SSH_AUTH_SOCK
