#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

# java behaves badly in non-reparenting window managers (e.g. xmonad)
export _JAVA_AWT_WM_NONREPARENTING=1

# Remap caps lock to escape
setxkbmap -option caps:escape

# Remap right alt to compose key
setxkbmap -option compose:ralt
