#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

# java behaves badly in non-reparenting window managers (e.g. xmonad)
export _JAVA_AWT_WM_NONREPARENTING=1

# Configure X
nm-applet &
cbatticon &
xbindkeys &
setxkbmap -option ctrl:nocaps
setxkbmap -option compose:ralt
xsetroot -cursor_name left_ptr -solid midnightblue &
xss-lock -- i3lock -n &
xautolock -time 10 -locker "i3lock -n" &
