vim.cmd('highlight clear SignColumn')
vim.cmd('highlight GitGutterAdd ctermfg=green')
vim.cmd('highlight GitGutterChange ctermfg=yellow')
vim.cmd('highlight GitGutterDelete ctermfg=red')
vim.cmd('highlight GitGutterChangeDelete ctermfg=yellow')
