require('core.config_plugins.completions')
require('core.config_plugins.lightline')
require('core.config_plugins.lsp')
require('core.config_plugins.mason')
require('core.config_plugins.solarized')
require('core.config_plugins.treesitter')
require('core.config_plugins.gitgutter')
